PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/spec/20100809.html#>
PREFIX shs: <http://example.org/#>

CONSTRUCT {
?Entity a prov:Entity.
?Entity shs:Time ?time .
?otherEntity prov:wasDerivedFrom ?Entity.
}
WHERE {
?Entity a prov:Entity.
?Entity shs:Time ?time .
?otherEntity prov:wasDerivedFrom ?Entity.
FILTER(?time = "2020-01-20T16:45:30" ^^xsd:dateTime) .
}
